### ISSUE TITLE
Crash after exploring for a while

### ISSUE THREAD

**Issue by SeriousCreeper** [Delocuro/Minestrapp-1.12#10]
Heya!

Was flying around, looking around for stuff, and eventually the game crashed with the following: https://pastebin.com/WkC4NtB3 

Loading the save file also crashes it right away. Used the latest version of minestrapp and forge. 

Let me know if you need me to test anything!

Cheers,
SC

**Comment by Delocuro** [comment]
Huh... do any of the other mods installed affect ore generation or block updates in any way? It looks like something happened during world gen that caused a block of Irradium Ore to enter some kind of infinite update loop. Apparently the compiled method names are obfuscated, though, and none of the lines of code it's referencing point to anything useful in my workspace (line 54 of the BlockIrradiumOre class is literally just a curly brace), so I'm having a hard time figuring out where the error is even happening.

If you're able to test the same seed with only 1 other mod installed at a time, that'll help narrow down the issue a lot. Since I've had no luck re-creating the issue, my best guess is that there might be some custom ore block that triggers block updates to its neighbors when generated, which could cause two simultaneous block updates if it generated next to Irradium Ore or something. That's a pretty wild guess though, so until I have some better idea of what mod or mods trigger the crash, I'm not sure how to go about fixing it...

**Comment by SeriousCreeper** [comment]
Seems to point to [this line](https://github.com/MinestrapTeam/Minestrapp-1.12/blob/1202120830e07375a52cb46960fc10a1a2615a73/main/java/minestrapp/block/BlockIrradiumOre.java#L91) (and also line 54 once at the end. I'm guessing your local code is a bit different by now?). 

But yeah i think i had some world gen affecting mods, unfortunately i got rid of the world already so i don't have the seed but i'll try with a few new worlds and see if i can run into it again!

**Comment by Delocuro** [comment]
Oh, woops, nevermind, I accidentally opened the Irradium Block class instead of the Irradium Ore class, lol - no wonder the code lines weren't pointing anywhere useful! That definitely helps narrow it down, then - it's something to do with the block trying to get the list of entities and schedule the next block update, but I still don't know why it's crashing. If you manage to recreate it, send me the world seed & coords you used - I'll do a test with just Minestrapp to see whether I can replicate the issue without any other mods installed.

**Comment by Delocuro** [comment]
Done quite a lot of worldgen since this was opened and have yet to run into any issues, so I'ma close this for now. If you run into it again, feel free to re-open this/make a new issue - can't discern much from the crash logs without being able to recreate the issue and test it.
