### ISSUE TITLE
An X-Ray Bug

### ISSUE THREAD

**Issue by RodrigoTaipe93** [Delocuro/Minestrapp-1.12#21]
Hello!

 

I got an issue with the mod. Is not a crash, rather a bug. I already tested it.

 

Whenever I don’t use the mod, I don’t get the “X-RAY” bug.

 

I will also share the list of mods that I use:

 

- https://imgur.com/a/dIEfbYI

**Comment by Delocuro** [comment]
Well that's interesting, lol. Evidently something's messing with the culling algorithms, because I've never encountered anything like that with just Minestrapp. Is Optifine the only mod you have installed that actually changes the render engine? Minestrapp doesn't actually alter the game's render engine in any way, so I genuinely have no idea why that's happening.

You also may want to try just running Minestrapp by itself and see if it does the same thing -- if it does, that could be some sort of OS compatibility issue, which is a much bigger issue...
