### ISSUE TITLE
Add Config Options - For Everything

### ISSUE THREAD

**Issue by ghost** [Delocuro/Minestrapp-1.12#37]
It would be great if Minestrap had config options for everything, to the same granularity as mods like Quark. It would be a lot easier for pack makers, such as myself, to tweak the mod's features to suit whatever pack it's being put into, rather than having to write hundreds of lines of recipe tweaks, JEI blacklists, loot table tweaks, etc.

**Comment by Delocuro** [comment]
Unfortunately, this really isn't feasible for a mod like Minestrapp. Quark was built from the ground up with the idea that every piece of content may or may not be utilized -- that's why there's no central tech or progression tree, and none of the recipes are heavily dependent on content from other sections of the mod.

Minestrapp, on the other hand, uses almost the exact opposite design philosophy. Almost every block and item in the mod can be used with seemingly unrelated content from other parts of the mod, so trying to make every single part modular would be a logistical nightmare. Removing even one item, like Tech Doodads or Grass Fibers, could make entire swaths of the mod unplayable in survival by proxy. I get the desire to hyper-customize things for use in modpacks, but it just fundamentally doesn't work particularly well with the way Minestrapp is designed -- which is probably why there aren't a ton of modpacks that feature it, lol.

I plan to try and add a bit more config customization support in M6, since we'll be re-developing it from scratch anyway, but for the time being, the current config support is about as much as we're able to do in M5.
