### ISSUE TITLE
Crash with sculls....

### ISSUE THREAD

**Issue by MisticaX** [Delocuro/Minestrapp-1.12#38]
Hello! I have the same problem with sculls, exactly when the scull on the hot bar. Game crashed and impossible to load the world again (thanks i have aroma). Also it is happened with machines. The crasher machine crashed the game when i tried to connect pipes (that game was lost forever therefore no logs saved)  
Mostly all mods up to date and sims like no conflicts. 
[mods.txt](https://github.com/MinestrapTeam/Minestrapp-1.12/files/3722536/mods.txt)
[crash-2019-10-13_23.54.23-server.txt](https://github.com/MinestrapTeam/Minestrapp-1.12/files/3722531/crash-2019-10-13_23.54.23-server.txt)
[latest.log](https://github.com/MinestrapTeam/Minestrapp-1.12/files/3722532/latest.log)
debug file more than 25mb can't load...

_Originally posted by @MisticaX in https://github.com/MinestrapTeam/Minestrapp-1.12/issues/35#issuecomment-541465734_

**Comment by Delocuro** [comment]
This appears to be an issue with FoamFix, not Minestrapp. The mod apparently assumes that every block with a directional blockstate supports all six directions, which isn't the case for many Minestrapp blocks. I can't do much about that, so I'd recommend reporting it to the FoamFix devs.

As far as the Crusher issue, that's a completely separate issue, which I've fixed in an upcoming hotfix that should be released in the next day or two. :)
