### ISSUE TITLE
Ticking player when crafting panels

### ISSUE THREAD

**Issue by scotty74864** [Delocuro/Minestrapp-1.12#41]
Hi! Been using Minestrapp for a few years now, and loving it! Thanks
But just this last few days Ive been getting a ticking player crash when crafting panels. Ive searched, Ive removed all recent mods and updated minestrapp. Not sure what to try next?

Any help appreciated, thanks :-)

[crash-2020-05-05_17.03.51-server.txt](https://github.com/MinestrapTeam/Minestrapp-1.12/files/4579288/crash-2020-05-05_17.03.51-server.txt)

**Comment by werty1124** [comment]
I can't seem to be able to reproduce it. Could you try it again with only minestrapp installed?

**Comment by scotty74864** [comment]
Minestrapp on its own works fine. The stranger thing is this is only happening with half my worlds.

**Comment by scotty74864** [comment]
Update:
Its Railcraft.
220 mods, two by two... 2nd last in the list. Long afternoon. Anyway, the crash happens when crafting panels, or going into a world where i have panels in my inventory.
Im going to keep playing around with it. Hope you find something :-)

**Comment by Delocuro** [comment]
Glad to hear you're enjoying the mod! Unfortunately, this is a known issue with a few items -- for whatever reason, Railcraft seems to add some inventory override method that tries to get all six facing states of any block without first checking whether the block actually contains all six states. This results in crashes with numerous other modded blocks which only have the four horizontal facing states.

I'd love to get this resolved, but the only thing I can really do on my end to solve it is add extra unused facing states to every horizontal block, which would be more or less impossible due to metadata limitations. I would recommend taking this issue to the Railcraft devs -- it's been an issue for a long time now, so I'm a bit surprised it's still not resolved...

**Comment by scotty74864** [comment]
Hi!
Been offline for a while, but thanks for the reply :-) Ive opened a ticket
with railcraft, but it looks like their pretty busy. Either way, I really
appreciate your time and thanks again
