### ISSUE TITLE
Deepstone infused redstone ore drops redstone with missing texture. 

### ISSUE THREAD

**Issue by mysteryblock** [Delocuro/Minestrapp-1.12#6]
As the title implies, I mined some redstone that had the deepstone texture, and it dropped redstone that has a missing texture. (pink and black box both in the game world and in my inventory) I haven't tested other forms of minestrapp redtstone yet, nor have I used the redstone with the missing texture to see if it functions the same.

**Comment by Delocuro** [comment]
Dang, that bug's back again? I was like 100% sure I had that fixed finally. :/ I'll take a loot at it again and see if I can replicate it & get it fixed for the next release - thanks for pointing that out!

**Comment by mysteryblock** [comment]
Just to be sure I'm using the latest version, I'm on v 5.0.0.A, as per the curse page.

**Comment by Delocuro** [comment]
There's actually a newer version out - 5.0.5A - but I haven't changed anything about Redstone Ore between that version and 5.0.0, so the bug is probably still there. Thanks for the remider though - Werty usually handles Curse, so I always forget I should probably post there whenever we release an update, lol.

**Comment by mysteryblock** [comment]
Ah, gotcha!

**Comment by Delocuro** [comment]
Fixed for the next release - I literally forgot to add one boolean, lmao
