### ISSUE TITLE
Config Options?

### ISSUE THREAD

**Issue by MasterEnderman** [Delocuro/Minestrapp-1.12#8]
Aren't there any or am I unable to find them?
Would like to configure some Aspects of the mods and tweak them to fit better in a pack I'm making.
  
CURRENT RUNNING LIST OF CONFIG OPTIONS
- [x] Toggle Invincium Gen
- [x] Make Glacial Invincium Minable
- [x] Toggles for all Ore gen.
- [x] Toggles for biome-specific Stone gen.
- [x] Toggles for plant gen (Savanna Grass, Tundra Grass, Berry Bushes, etc).

**Comment by Delocuro** [comment]
There aren't any yet, but we plan to add a proper config in a future release. In the meantime, let me know what specific options you'd like to see in the config file - I'll be taking any suggestions into account when I start implementing it.

**Comment by medsal15** [comment]
Disabling models added by Minstrapp.

**Comment by MasterEnderman** [comment]
Options to configure the oregeneration would be very nice.

**Comment by Delocuro** [comment]
Sounds good - added a todo list of all the currently suggested config options above.

And @medsal15 - planning to make that an option, but it'll be done via resource packs rather than config options. I'll make a new issue for that so I remember to get it done for the next major update.

**Comment by MasterEnderman** [comment]
Could you make a config option for overwriting all vanilla stone generation and just use the ones from minestrapp?

**Comment by Delocuro** [comment]
You mean like prevent Vanilla Stone from generating at all? I could potentially add an option for that, but that one would be a bit more complicated. The way Stone gen works now is that every biome is assigned one of 5 Stone types based on its temperature - Red Rock for warm biomes, Coldstone for cool biomes, Icestone for snowy biomes, Oceanstone for Oceans & Mushroom Islands, and Vanilla Stone for all the other "mild" biomes like Forests or Plains. The generator then goes through all the Stone in the world and replaces it with the proper biome stone, or that stone type's Deep variant if it's below a certain depth.

In order to prevent Vanilla Stone from generating, we'd need some other type of Stone to replace it - the easiest solution would be replacing it with Red Rock or Coldstone, those being the two most "generic" types of stone out of the 4 Minestrapp adds. However, that wouldn't make a ton of thematic sense for those stone types to generate in moderate biomes, and it could make moderate biomes look kinda gross, since Red Rock doesn't look great with Vanilla Dirt (hence why we added Clay Soil in M5), and Coldstone works well with the Extreme Hills/Tundra grass colors, but not so much with the bright grass of Forest or Jungle biomes.

We'd almost need config options for what stone types should generate in each individual biome, but that'd require a complete re-code of the whole Stone-gen engine, so it probably won't happen in the next update. If you've got a specific use case scenario you're thinking about using this for, let me know, though - there might be a simpler solution that could reach the same goal.

**Comment by MasterEnderman** [comment]
Guess the idea with the stone replacement isn't that great, but I have another idea. Maybe a config to change the generation of rocks like slate, so you can tweak the generation size, generation Chance and so on.

**Comment by Delocuro** [comment]
Again, that'd be a hard one to implement. We could do that for the normal ores easily enough, but Slate doesn't actually generate in veins. Instead, each biome category is assigned three of the four decorative stone variants - Granite, Diorite, Andesite, and Slate - that can generate in those biomes. Then, during generation, any biomes that have Slate as one of the three selected types replace all of the missing fourth type of stone (Granite, Diorite, or Andesite) with Slate, thus making it so that Slate always generates at the same rates as the Vanilla three, and doesn't overcrowd the underground with decorative stones.

In order to change the generation rate of Slate, therefore, we'd need to completely override the Vanilla generation of Granite, Andesite, and Diorite, which I'm not even sure how to go about doing without creating a brand new world type or something. What I could do is add options for which 3 decorative stones spawn in each biome, but that's about as close as I can get.

Keep in mind, we don't want to add config options just for the sake of adding config options. If there's specific use-cases you have in mind for these, let me know, but the more config options we add, the more complicated it becomes to add new features in the future.

**Comment by Delocuro** [comment]
If anyone has any further config suggestions, feel free to make a new issue for them - closing this one since all the bullets listed above are now implemented! :D
