### ISSUE TITLE
Register things in the OreDictionnary

### ISSUE THREAD

**Issue by medsal15** [Delocuro/Minestrapp-1.12#9]
- [x] Mossy cobblestones and mossy bricks should be registered as `blockMossy`.
- [x] Bricks aren't registered as `bricksStone`.
- [x] Salt ore should be registered as `oreSalt`. Block of salt should be registered as `blockSalt`. Salt might need to be registered as `gemSalt`.
- [x] Blazium ore should be registered as `oreBlazium`.
- [x] Additionals blocks of redstone should be registered as `blockRedstone`.
- [x] Unstable block of Irradium should be registered as `blockIrradium`.
- [x] Sunstone should be registered as `blockSunstone`.
- [x] Block of glacierite should be registered as `blockGlacierite`.
- [x] Chunks should be registered as dusts/ores depending on their uses.
- [x] Tallow might be registered as `tallow`.
- [ ] Reinforced sticks might be registered as `stickWood`.

**Comment by Delocuro** [comment]
Awesome, that helps a lot - I'm never totally sure what should be registered to OreDict, lol. I'll make sure those are all added for 5.3.0!

**Comment by Delocuro** [comment]
Done - these should be working for 5.2.1! The only one I didn't add is Reinforced Sticks being registered as stickWood. Registering Reinforced Sticks as normal Sticks could not only create a lot of recipe logic weirdness (crafting Reinforced Sticks with Reinforced Sticks, for example), but also could create some conflicts with a few future recipes I want to add eventually. If there's a commonly used oreDict name for strengthened Stick-like items, let me know, but otherwise I'm leaving that one out for now.
